"""
Helper script: appends Section 12 (Wavelet-Based Reverberation Suppression)
to the exploration notebook and then deletes itself.
"""
import json
import pathlib

NB_PATH = pathlib.Path(__file__).with_name("reverberation_artifact_report.ipynb")

# ---------------------------------------------------------------------------
# Markdown cell
# ---------------------------------------------------------------------------
MARKDOWN_LINES = [
    "## 12) Wavelet-Based Reverberation Suppression (Synthetic A-line Demo)\n",
    "\n",
    "### Physics background\n",
    "\n",
    "An ultrasound A-line measured in the presence of high-impedance reflectors\n",
    "can be modelled as\n",
    "\n",
    "$$\n",
    "s(t) = \\sum_{i} a_i \\cdot p(t - \\tau_i)\n",
    "      + \\sum_{j,k} r_{j,k} \\cdot p\\!\\left(t - \\tau_j - k\\,\\Delta\\tau_j\\right)\n",
    "$$\n",
    "\n",
    "where $p(t)$ is the transducer pulse, $\\tau_i$ are the true round-trip\n",
    "delays of genuine reflectors, and the double sum represents the *reverberation\n",
    "train*: periodic ghost echoes at multiples $k\\,\\Delta\\tau_j$ past each\n",
    "strong reflector ($\\Delta\\tau_j = \\tau_j$ for a simple flat reflector).\n",
    "\n",
    "### Why wavelets?\n",
    "\n",
    "* **Symlets (sym8)** are the closest orthogonal-wavelet match to a\n",
    "  Gaussian-modulated sinusoid -- the canonical ultrasound pulse shape -- so\n",
    "  each genuine reflector produces a *single, compact* cluster of large\n",
    "  coefficients at the correct depth.\n",
    "* A **Stationary (a-trous) Wavelet Transform (SWT)** is used instead of\n",
    "  the standard DWT because it is *shift-invariant*: DWT decimation would\n",
    "  shift peak positions between levels, making periodic detection unreliable.\n",
    "* Reverberations are *periodic* in the SWT coefficient domain with the same\n",
    "  period at every scale because SWT preserves the full sample count.\n",
    "\n",
    "### Algorithm: Coefficient Correlation Suppression\n",
    "\n",
    "1. Compute the SWT to $L = 6$ levels.\n",
    "2. At each detail level $\\ell$, locate *primary-peak* positions\n",
    "   $p_0$ where $|c_\\ell[p_0]| > \\mu + \\sigma_{\\text{thr}}\\cdot\\sigma$\n",
    "   (data-adaptive threshold).\n",
    "3. Predict reverberation positions $p_0 + m\\,\\Delta k$ with\n",
    "   $\\Delta k = \\lfloor \\Delta\\tau \\cdot f_s \\rceil$, $m = 1, 2, \\ldots$\n",
    "4. Apply a soft suppression window centred on each predicted site:\n",
    "   $c_\\ell[p_0 + m\\,\\Delta k \\pm w] \\leftarrow\n",
    "    g(m)\\,c_\\ell[p_0 + m\\,\\Delta k \\pm w]$,\n",
    "   where $g(m) = 1 - \\alpha\\,e^{-\\beta(m-1)}$ decreases with order\n",
    "   to reduce the risk of distorting genuine weak reflectors.\n",
    "5. Reconstruct via the inverse SWT.\n",
    "\n",
    "> **Note on the homomorphic approach.** For multiplicative gain fields\n",
    "> (frequency-dependent tissue attenuation), one could log-transform the\n",
    "> *envelope* to convert the problem into an additive one before decomposing.\n",
    "> Here the reverberations are already additive (linear superposition) and the\n",
    "> SWT coefficients are signed, so we work directly in the wavelet domain\n",
    "> without a log-transform.\n",
]

# ---------------------------------------------------------------------------
# Code cell  (triple-quote docstrings replaced with # comments to avoid
# conflicting with Python's string-literal parsing in this helper script)
# ---------------------------------------------------------------------------
CODE_LINES = [
    "# =============================================================================\n",
    "# Section 12 - Wavelet-Based Reverberation Suppression\n",
    "# Physics-to-math mapping and 'Coefficient Correlation' method\n",
    "# =============================================================================\n",
    "\n",
    "import numpy as np\n",
    "import pywt\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "rng = np.random.default_rng(42)\n",
    "\n",
    "# -- 1. SYNTHETIC A-LINE ------------------------------------------------------\n",
    "# Signal model:\n",
    "#   s(t) = sum_i a_i * p(t-tau_i)  +  sum_{j,k} r_{j,k} * p(t-tau_j-k*dtau_j)\n",
    "\n",
    "FS      = 40e6      # sampling frequency [Hz]  (40 MHz typical for medical US)\n",
    "C_SOUND = 1540.0   # speed of sound in soft tissue [m/s]\n",
    "DURATION = 100e-6  # record length [s]  => ~7.7 cm depth range\n",
    "N        = int(FS * DURATION)\n",
    "t_axis   = np.arange(N) / FS\n",
    "depth_mm = t_axis * C_SOUND / 2.0 * 1e3   # two-way time -> depth [mm]\n",
    "\n",
    "F0    = 5e6          # pulse centre frequency [Hz]\n",
    "BW    = 3e6          # -6 dB bandwidth [Hz]\n",
    "SIGMA = 1.0 / (np.pi * BW)   # Gaussian envelope width [s]\n",
    "\n",
    "\n",
    "def modulated_pulse(t, t0, amplitude=1.0):\n",
    "    # Gaussian-modulated sinusoid - canonical US pulse  p(t - t0)\n",
    "    env = np.exp(-0.5 * ((t - t0) / SIGMA) ** 2)\n",
    "    return amplitude * env * np.cos(2 * np.pi * F0 * (t - t0))\n",
    "\n",
    "\n",
    "# Two high-impedance objects:  (depth [m], amplitude, decay per bounce)\n",
    "OBJECTS = [\n",
    "    dict(depth=0.020, amp=1.00, decay=0.45),   # Object 1 at 2.0 cm\n",
    "    dict(depth=0.035, amp=0.60, decay=0.35),   # Object 2 at 3.5 cm\n",
    "]\n",
    "N_REVERB = 4   # number of reverberation orders per object\n",
    "\n",
    "aline = np.zeros(N, dtype=np.float64)\n",
    "for obj in OBJECTS:\n",
    "    tau = 2.0 * obj['depth'] / C_SOUND   # round-trip delay [s]\n",
    "    # Primary reflection (k=0 in the signal model)\n",
    "    aline += modulated_pulse(t_axis, tau, amplitude=obj['amp'])\n",
    "    # Reverberation train: echoes at tau + k*delta_tau, delta_tau = tau\n",
    "    for k in range(1, N_REVERB + 1):\n",
    "        r_amp = obj['amp'] * (obj['decay'] ** k)\n",
    "        aline += modulated_pulse(t_axis, tau + k * tau, amplitude=r_amp)\n",
    "\n",
    "# White Gaussian noise (SNR ~ 20 dB)\n",
    "aline += rng.normal(scale=0.01, size=N)\n",
    "\n",
    "# -- 2. STATIONARY WAVELET TRANSFORM (SWT) ------------------------------------\n",
    "# sym8 closely matches the Gaussian-modulated US pulse, giving compact and\n",
    "# well-localised coefficients per reflector.\n",
    "# SWT is shift-invariant (no decimation), so peak sample indices map\n",
    "# directly to physical depths without inter-level translation artefacts.\n",
    "\n",
    "WAVELET  = 'sym8'\n",
    "N_LEVELS = 6\n",
    "\n",
    "# swt() returns [(cA_1, cD_1), ..., (cA_L, cD_L)], index 0 = finest scale.\n",
    "swt_coeffs  = pywt.swt(aline, WAVELET, level=N_LEVELS, norm=True)\n",
    "detail_list = [cD for (_, cD) in swt_coeffs]   # detail bands\n",
    "approx_list = [cA for (cA, _) in swt_coeffs]   # approximation bands\n",
    "\n",
    "# -- 3. COEFFICIENT CORRELATION SUPPRESSION -----------------------------------\n",
    "# For each primary-peak position p0 detected in a detail band, reverberation\n",
    "# positions are p0 + m * delta_k  (m = 1, 2, ...) where\n",
    "#   delta_k = round(delta_tau * FS).\n",
    "# Because SWT preserves the full sample count at every level, delta_k is\n",
    "# scale-independent -- the same integer shift applies everywhere.\n",
    "\n",
    "\n",
    "def suppress_reverb_in_band(cD, delta_k, n_orders=N_REVERB + 2,\n",
    "                             thresh_sigma=2.5, strength=0.90):\n",
    "    # Suppress periodic reverberation coefficients in one SWT detail band.\n",
    "    #\n",
    "    # Parameters\n",
    "    # ----------\n",
    "    # cD           : (N,) detail coefficients at one scale\n",
    "    # delta_k      : int  reverberation period in samples (= round(delta_tau*FS))\n",
    "    # n_orders     : int  number of reverberation orders to hunt\n",
    "    # thresh_sigma : float  threshold = mean + thresh_sigma * std\n",
    "    # strength     : float [0,1]  max suppression gain applied to echoes\n",
    "    #\n",
    "    # Returns cleaned (N,) array.\n",
    "    cleaned   = cD.copy()\n",
    "    energy    = np.abs(cleaned)\n",
    "    threshold = energy.mean() + thresh_sigma * energy.std()\n",
    "\n",
    "    # Non-maximum suppression: keep only local maxima in a +-half_win window\n",
    "    half_win = max(1, delta_k // 4)\n",
    "    above    = np.where(energy > threshold)[0]\n",
    "    primaries = []\n",
    "    for pos in above:\n",
    "        lo, hi = max(0, pos - half_win), min(N, pos + half_win + 1)\n",
    "        if energy[pos] >= energy[lo:hi].max():\n",
    "            primaries.append(int(pos))\n",
    "\n",
    "    for p0 in primaries:\n",
    "        for m in range(1, n_orders + 1):\n",
    "            center = p0 + m * delta_k\n",
    "            if center >= N:\n",
    "                break\n",
    "            # Window broadens slightly with order (pulse smearing from attenuation)\n",
    "            win = half_win + m\n",
    "            lo  = max(0, center - win)\n",
    "            hi  = min(N, center + win + 1)\n",
    "            # Soft gain: g(m) = 1 - alpha * exp(-beta*(m-1))\n",
    "            # Stronger suppression for early echoes (large amplitude, most\n",
    "            # distorting); gentler for late echoes (weak, harder to distinguish\n",
    "            # from genuine reflectors).\n",
    "            gain = 1.0 - strength * np.exp(-0.3 * (m - 1))\n",
    "            cleaned[lo:hi] *= gain\n",
    "\n",
    "    return cleaned\n",
    "\n",
    "\n",
    "# Reverberation periods for both objects in samples\n",
    "delta_k = {\n",
    "    'obj1': int(round(2.0 * OBJECTS[0]['depth'] / C_SOUND * FS)),\n",
    "    'obj2': int(round(2.0 * OBJECTS[1]['depth'] / C_SOUND * FS)),\n",
    "}\n",
    "\n",
    "cleaned_details = []\n",
    "for lvl, cD in enumerate(detail_list):\n",
    "    # Coarsest level captures slow trends -- skip suppression there to\n",
    "    # preserve baseline structure and avoid over-processing.\n",
    "    if lvl >= N_LEVELS - 1:\n",
    "        cleaned_details.append(cD)\n",
    "        continue\n",
    "    cD_c = suppress_reverb_in_band(cD, delta_k['obj1'])\n",
    "    cD_c = suppress_reverb_in_band(cD_c, delta_k['obj2'])\n",
    "    cleaned_details.append(cD_c)\n",
    "\n",
    "# -- 4. INVERSE SWT RECONSTRUCTION --------------------------------------------\n",
    "cleaned_swt = [(approx_list[i], cleaned_details[i]) for i in range(N_LEVELS)]\n",
    "aline_clean = pywt.iswt(cleaned_swt, WAVELET)\n",
    "\n",
    "# -- 5. VISUALISATION ---------------------------------------------------------\n",
    "fig, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=True)\n",
    "\n",
    "axes[0].plot(depth_mm, aline, color='steelblue', lw=0.7, label='Original A-line')\n",
    "for obj in OBJECTS:\n",
    "    axes[0].axvline(obj['depth'] * 1e3, color='crimson', ls='--', lw=0.9,\n",
    "                    label=f\"Reflector @ {obj['depth']*100:.1f} cm\")\n",
    "axes[0].set_ylabel('Amplitude')\n",
    "axes[0].set_title('Original A-line  (primary reflections + reverberation train)')\n",
    "axes[0].legend(fontsize=8, ncol=2)\n",
    "axes[0].grid(True, alpha=0.3)\n",
    "\n",
    "axes[1].plot(depth_mm, aline_clean, color='darkorange', lw=0.7,\n",
    "             label='Cleaned A-line')\n",
    "for obj in OBJECTS:\n",
    "    axes[1].axvline(obj['depth'] * 1e3, color='crimson', ls='--', lw=0.9)\n",
    "axes[1].set_ylabel('Amplitude')\n",
    "axes[1].set_title('Cleaned A-line  (SWT coefficient-correlation suppression, sym8)')\n",
    "axes[1].legend(fontsize=8)\n",
    "axes[1].grid(True, alpha=0.3)\n",
    "\n",
    "residual = aline - aline_clean\n",
    "axes[2].plot(depth_mm, residual, color='mediumpurple', lw=0.7,\n",
    "             label='Residual (suppressed signal)')\n",
    "# Mark expected reverberation depths for reference\n",
    "first_reverb_labeled = False\n",
    "for obj in OBJECTS:\n",
    "    tau = 2.0 * obj['depth'] / C_SOUND\n",
    "    for k in range(1, N_REVERB + 1):\n",
    "        reverb_depth_mm = (tau + k * tau) * C_SOUND / 2.0 * 1e3\n",
    "        lbl = 'Expected reverb' if not first_reverb_labeled else ''\n",
    "        axes[2].axvline(reverb_depth_mm, color='gray', ls=':', lw=0.7, label=lbl)\n",
    "        first_reverb_labeled = True\n",
    "axes[2].set_xlabel('Depth  [mm]')\n",
    "axes[2].set_ylabel('Amplitude')\n",
    "axes[2].set_title('Residual = Original - Cleaned  '\n",
    "                  '(should align with predicted reverberation depths)')\n",
    "axes[2].legend(fontsize=8)\n",
    "axes[2].grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# -- 6. QUANTITATIVE METRICS --------------------------------------------------\n",
    "\n",
    "\n",
    "def window_energy(sig, center_sample, half_width):\n",
    "    lo = max(0, center_sample - half_width)\n",
    "    hi = min(len(sig), center_sample + half_width + 1)\n",
    "    return float(np.sum(sig[lo:hi] ** 2))\n",
    "\n",
    "\n",
    "hw = int(round(1e-6 * FS))   # +-1 us window around each feature\n",
    "\n",
    "print('-' * 62)\n",
    "print(f\"{'Location':<34}  {'Original':>9}  {'Cleaned':>9}  {'Reduction':>9}\")\n",
    "print('-' * 62)\n",
    "\n",
    "for obj in OBJECTS:\n",
    "    tau = 2.0 * obj['depth'] / C_SOUND\n",
    "    p_samp = int(round(tau * FS))\n",
    "    e_orig = window_energy(aline,       p_samp, hw)\n",
    "    e_cln  = window_energy(aline_clean, p_samp, hw)\n",
    "    label  = f\"Primary  @ {obj['depth']*100:.1f} cm\"\n",
    "    print(f\"{label:<34}  {e_orig:>9.4f}  {e_cln:>9.4f}  \"\n",
    "          f\"{(1 - e_cln / max(e_orig, 1e-12)) * 100:>8.1f}%\")\n",
    "    for k in range(1, N_REVERB + 1):\n",
    "        c_samp = int(round((tau + k * tau) * FS))\n",
    "        if c_samp >= N:\n",
    "            break\n",
    "        e_orig = window_energy(aline,       c_samp, hw)\n",
    "        e_cln  = window_energy(aline_clean, c_samp, hw)\n",
    "        reverb_depth_mm = (tau + k * tau) * C_SOUND / 2.0 * 1e3\n",
    "        label  = f\"  Reverb k={k} @ {reverb_depth_mm:.1f} mm\"\n",
    "        print(f\"{label:<34}  {e_orig:>9.4f}  {e_cln:>9.4f}  \"\n",
    "              f\"{(1 - e_cln / max(e_orig, 1e-12)) * 100:>8.1f}%\")\n",
    "\n",
    "print('-' * 62)\n",
]

# ---------------------------------------------------------------------------
# Append to notebook
# ---------------------------------------------------------------------------
with open(NB_PATH) as fh:
    nb = json.load(fh)

md_cell = {
    "cell_type": "markdown",
    "metadata": {},
    "source": MARKDOWN_LINES,
}

code_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": CODE_LINES,
}

nb["cells"].extend([md_cell, code_cell])

with open(NB_PATH, "w") as fh:
    json.dump(nb, fh, indent=1)

print(f"Done. Notebook now has {len(nb['cells'])} cells.")
pathlib.Path(__file__).unlink()
